
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'adagrad adam add_layer compile evaluate filepath fit float input int linear load output relu rmsprop sequential sgd sigmoid split tanh test train use\n    start : LoadFile Split Use Addl Addl2 Compile Fit Evaluate\n    \n    LoadFile : load filepath\n    \n    Split : split splitinput splitoutput\n    \n    splitinput : input int int\n    \n    splitoutput : output int\n    \n    Use : use TON\n    \n    TON : sequential\n    \n    Addl : add_layer int int Act\n    \n    Addl2 : add_layer int Act Addl2\n    \n    Addl2 :\n    \n    Act : relu\n        | sigmoid\n        | tanh\n        | linear\n    \n    Compile : compile Optimizer\n    \n    Optimizer : adam\n              | adagrad\n              | sgd\n              | rmsprop\n    \n    Fit : fit epoch BatchSize\n    \n    epoch : int\n    \n    BatchSize : int\n    \n    Evaluate : evaluate\n    '
    
_lr_action_items = {'fit':([24,34,35,36,37,38,],[32,-16,-19,-15,-17,-18,]),'sigmoid':([23,26,],[27,27,]),'linear':([23,26,],[28,28,]),'adam':([25,],[34,]),'load':([0,],[3,]),'relu':([23,26,],[30,30,]),'rmsprop':([25,],[35,]),'sgd':([25,],[38,]),'input':([4,],[8,]),'add_layer':([10,14,15,17,27,28,29,30,31,39,],[16,-6,-7,22,-12,-14,-13,-11,-8,22,]),'int':([8,12,13,16,20,22,32,40,41,],[13,18,19,20,23,26,40,-21,45,]),'$end':([2,42,43,],[0,-23,-1,]),'split':([1,6,],[4,-2,]),'tanh':([23,26,],[29,29,]),'compile':([17,21,27,28,29,30,31,39,44,],[-10,25,-12,-14,-13,-11,-8,-10,-9,]),'sequential':([9,],[15,]),'evaluate':([33,45,46,],[42,-22,-20,]),'filepath':([3,],[6,]),'adagrad':([25,],[37,]),'output':([7,19,],[12,-4,]),'use':([5,11,18,],[9,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'TON':([9,],[14,]),'LoadFile':([0,],[1,]),'start':([0,],[2,]),'splitoutput':([7,],[11,]),'Optimizer':([25,],[36,]),'BatchSize':([41,],[46,]),'Use':([5,],[10,]),'Addl2':([17,39,],[21,44,]),'Addl':([10,],[17,]),'epoch':([32,],[41,]),'splitinput':([4,],[7,]),'Compile':([21,],[24,]),'Evaluate':([33,],[43,]),'Split':([1,],[5,]),'Fit':([24,],[33,]),'Act':([23,26,],[31,39,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> LoadFile Split Use Addl Addl2 Compile Fit Evaluate','start',8,'p_start','test.py',120),
  ('LoadFile -> load filepath','LoadFile',2,'p_LoadFile','test.py',127),
  ('Split -> split splitinput splitoutput','Split',3,'p_Split','test.py',136),
  ('splitinput -> input int int','splitinput',3,'p_splitinput','test.py',142),
  ('splitoutput -> output int','splitoutput',2,'p_splitoutput','test.py',155),
  ('Use -> use TON','Use',2,'p_Use','test.py',167),
  ('TON -> sequential','TON',1,'p_TON','test.py',175),
  ('Addl -> add_layer int int Act','Addl',4,'p_Addl','test.py',183),
  ('Addl2 -> add_layer int Act Addl2','Addl2',4,'p_Addl2','test.py',197),
  ('Addl2 -> <empty>','Addl2',0,'p_Addl2empty','test.py',213),
  ('Act -> relu','Act',1,'p_Act','test.py',220),
  ('Act -> sigmoid','Act',1,'p_Act','test.py',221),
  ('Act -> tanh','Act',1,'p_Act','test.py',222),
  ('Act -> linear','Act',1,'p_Act','test.py',223),
  ('Compile -> compile Optimizer','Compile',2,'p_Compile','test.py',230),
  ('Optimizer -> adam','Optimizer',1,'p_Optimizer','test.py',238),
  ('Optimizer -> adagrad','Optimizer',1,'p_Optimizer','test.py',239),
  ('Optimizer -> sgd','Optimizer',1,'p_Optimizer','test.py',240),
  ('Optimizer -> rmsprop','Optimizer',1,'p_Optimizer','test.py',241),
  ('Fit -> fit epoch BatchSize','Fit',3,'p_Fit','test.py',247),
  ('epoch -> int','epoch',1,'p_epoch','test.py',257),
  ('BatchSize -> int','BatchSize',1,'p_BatchSize','test.py',263),
  ('Evaluate -> evaluate','Evaluate',1,'p_Evaluate','test.py',269),
]
